<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite hostname="DESKTOP-U76KVEG" name="Test for release 10.3" tests="7" failures="1" timestamp="14 Mar 2023 23:08:21 GMT" time="10.296" errors="0">
  <testcase name="loginValidation" time="0.597" classname="sauceDemoTestNgTest.SauceDemoTestNG"/>
  <testcase name="failedLoginValidation" time="0.354" classname="sauceDemoTestNgTest.SauceDemoTestNG">
    <failure type="java.lang.AssertionError" message="expected [https://www.saucedemo.com/inventory.html] but found [https://www.saucedemo.com/]">
      <![CDATA[java.lang.AssertionError: expected [https://www.saucedemo.com/inventory.html] but found [https://www.saucedemo.com/]
	at sauceDemoTestNgTest.SauceDemoTestNG.failedLoginValidation(SauceDemoTestNG.java:95)
... Removed 29 stack frames]]>
    </failure>
  </testcase> <!-- failedLoginValidation -->
  <testcase name="testLogin" time="0.55" classname="sauceDemoTestNgTest.EndToEndTesting"/>
  <testcase name="testInventory" time="0.288" classname="sauceDemoTestNgTest.EndToEndTesting"/>
  <testcase name="testCartPage" time="0.107" classname="sauceDemoTestNgTest.EndToEndTesting"/>
  <testcase name="testCheckOutStepOne" time="0.448" classname="sauceDemoTestNgTest.EndToEndTesting"/>
  <testcase name="testCheckOutStepTwo" time="0.107" classname="sauceDemoTestNgTest.EndToEndTesting"/>
</testsuite> <!-- Test for release 10.3 -->
